spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: audwhd951@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # 개발 중이면 update, 운영에선 validate 추천
    show-sql: true
  thymeleaf:
    cache: false